language: node_js
node_js:
- 4.1.2
services:
- mongodb
before_install:
- npm install -g grunt-cli
install:
- npm install
deploy:
  provider: heroku
  api_key:
    secure: o7xhGzOmQW4aGce6+9F65HfvFyGku7iPh+Lfnna3RdXJy+3oEs1ol5Qxoq4gF9hV2z2luA3as9SBtFoM/9v1fuJZpc43wxAbn3xoAziIL1aAZl0mm4T03Cjs5Ym/jbXtLr+DRSJesCj0RaNDl12NIcO0LtGtm9weLBrdEoMHfDK5SEd+77ipIX0UzgUrklllRtLdbiZGY812fXL1P0huIIN+oayfSJpvKcEuK/4bHKptiWv9G5PSo9lIOghWMb+3WPchny7lwKBUpKjUCgMQRMdE81s3uuMhRhoQxCjsf3yT8F20JU9FhfYV6siXmUahBNRWQgaT80erbeb5bALc0W/8Im1Mqj5X5irH3fDLixpVPKZVCLXWx4LlOE4rFgq/CcPmXNCZEbVznQ8oG4xWHfQReowY1qFX6ksbuCDFtdySqW/VA6WRtJYgidVNIJmG7rVgXpGkHs9UGkiSsd6FLiRiDsAzf+TY4PDpnIfNf3IAlFhWHc/G6aFeP9sx/+HrfSHSCqGvXupv3XSPExkyMCI/gWogZ4izwZ5aad1E8tLoxiyy8euho80TErznHJfRcNNgn4fNQYB5FZ+9ZwTVkiUjSMzBE1Hi/TzFXiC5MJ9TIB/HWxboiWc+twuh9kJ1DAHXGlH+s9FVdhiigTM5fW/nODMMeVrby67p/5mSI8U=
  app:
    production: sodocan
    master: sodocan-staging
  on:
    repo: sodocan/sodocan.js
